{% set name = "net-ssh" %}
{% set version = "6.0.2" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 8de26e53c0f969a70190071c5e94ac6bb19bbe2f1047e222c4bca25f4155c44d

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby >=2.5
  run:
    - ruby >=2.5

test:
  commands:
    - ruby -r net/ssh -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: A pure-Ruby implementation of the SSH2 client protocol.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/net-ssh/{{ name }}

extra:
  recipe-maintainers:
    - conda-forge/ruby
    - benhuff
    - oblute
