travis:
  secure:
    BINSTAR_TOKEN: RZW/VYKXdB5qDwJh/mMWQ+XfGBDkiozAfNIHsUU/297Xd1EbP/2HXLa7RqJvmb43Q0YH8Uhva7nbMTOlK5ykyabQ1LLj5T9NaZv7YL41dBD5wLFYSFUeyHvgi1noxysNANb3yLwRq6sKJFyUft4Xo14fs5MktRw/dlP8zvg7CV5a5gDuB6PYL+svdYoetWxq0UWzvP7d/eq0GFR9cf/LkSBQb3kLDvg/+7o4rjLrgDEe++7uteq+vTV1vkHTjGWjFuj8ARH1gdeteO8bPaBSy64Xw530ziiuH2nM1sF90CqYDtIskEQXHJtO3kyeqMdvI9SjcL41Az/FrmVJKirwG4WvO53xdRjtMVv0zjebjU8ihPP+QXLy7JOW0XfYBtH89WG2CIGx7/alBucLaKYJsLgT+TpbVKTVT9FQeyFAlpG00UvIwRr5RAMkcKylXEHDoY1vHTmavEsMfJQv42+GOwxicYXr1W9qux51BypuDXbCJqH/3mX/lMvvwoT9ofI7QSosLEzE0TFtu+e5Jr1hkPdWkSRfrekmQz2uL4spPjeP6Jzvgx6BMMC7We2Rx8rjOYvSZEnaDCessN9SSUXYP1eZDj9ERzN/UPevXX8TjYoOZgw7Rs11zModPv+3a9FcYSj/No7iZDaOou4vNypFLcDmrzYQL9DjZ0Pap7UmO10=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
