travis:
  secure:
    BINSTAR_TOKEN: zkixDTkAqE5fYWHcf8/c7A8QlGMLw0ORTOz/lgwI38f/J8V/emPWp6jRnSOsatwtybdvLLTnguctgBjnVRgBWxpNYZ5dzVTMyJhK/KjXEqI+V/eS9xHND9hBJjD49IFZHXQL+yWZpoFCeYEjDdBvji1GR3AIaw2eRLQhu6gUL6Ofv7qXvKnsWKkLWPdF2c3eY4/X9DKYmn9XPV1ZqrXbTR9Mm/x7uAlt76wr2aiPl4Hyy9pw/z0TZX5EouTZGuWbDbkZDRzrO1UZcYaXkHvY8AAlDdMsGjlmrhOMVH9AdY+a11SXrZM93OqCah9UE1fW1az0v0xNQoxaNmEU87KDOzEwKxdPg1Ewj49l6RQtLKjT/e4Cgryzxz4gixqGZIQkZN6he2koTZBeCJgyrrHeUJZWQr6nrBpGndpl7f0FmWoWauBjTIqQl9r1BLICnTcBcbj2OQyEVVZwSG+/Iez3OW0OX7tVuQixPM4u1oZwuI46QsJr3Na8RpBK/8LnNJAXmLCkCsmTMP+qc8iVJi6r3I3EajGTz/eWX/kjyHu6kR/dKGoE/w48m/tmG7YZfvyflPXeKBhk9GwlmKWQEGH5W42z0qI9Kv3ksH9Py45dSsgJAHtP/xE18oq1oAutUCEZWy7ofbOfR5Bo6diPvqdopoBm1/GdOymABSrNls8tfyI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
